### ISSUE TITLE
Adding OPENAI_API_BASE

### ISSUE THREAD

**Issue by StudyingLover** [Welltested-AI/fluttergpt#114]
Hope can add my own API endpoint in setting

**Comment by ishaan-jaff** [comment]
Hi @StudyingLover I’m the maintainer of LiteLLM - we allow you to create a proxy server to call 100+ LLMs, and I think it can solve your problem

Try it here: https://docs.litellm.ai/docs/proxy_server. I'd love your feedback on how we can make it better for you 

## Usage
```python
import openai
openai.api_base = "http://0.0.0.0:8000/" # proxy url
print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```

## Creating a proxy server 
Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```


Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

**Comment by samyakkkk** [comment]
This will be worked on in the future. Closing this for now.
