### ISSUE TITLE
Doesnt work in Android Studio

### ISSUE THREAD

**Issue by Savaesc** [Welltested-AI/fluttergpt#115]
Installed it in Android Studio Giraffe. Added OpenApi key in Settings-Tools-FlutterGPT. Restarted many times. Reinstalled the plugin several times. Paying for OpenApi GPT-4 (Any issue?)

I simply cannot get it to work. Any idea why?

MacOs Senoma M1 

Thanks

**Comment by ren276** [comment]
Run the extension from the debug , which can help

**Comment by doitwithdk** [comment]
Hey @Savaesc ,

Quick favor—could you give the latest version a spin? 🔄 If that pesky issue is still hanging around, a quick screen recording would be awesome! 🎥 Your insights help us squash bugs like superheroes.

Also make sure you have VSCode extension for Dart and Flutter installed already.  

Just a heads up, if we can't recreate the hiccup on our end, we might need to close the ticket. Your help in nailing down the details means the world to us!

Thanks a bunch for your time! 🚀

**Comment by doitwithdk** [comment]
Closing the issue as we were not able reproduce the issue and haven't heard back from @Savaesc .
