### ISSUE TITLE
[Doc]: Add Documentation for activate Function in extension.ts

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#125]
### Is your feature request related to a problem?

The `activate` function lacks documentation, making it difficult for new contributors to understand its purpose and functionality.

### Describe the solution that you'd like

Add comprehensive **JSDoc comments** to the `activate` function, detailing its responsibilities, parameters, and any important information about its inner workings.

### Describe alternatives that you have considered

Alternatively, a separate documentation file could be created, but **in-line documentation is preferred** for ease of access.

### Additional Information

Familiarize yourself with the `activate` function's code and the extension's overall workflow.

### Acceptance Criteria

1. JSDoc comments are present for the `activate` function.
2. Comments are clear, concise, and accurately describe the function's behavior.

**Comment by superiorsd10** [comment]
Hello @yatendra2001 👋
I want to work on this issue, so please consider assigning it to me.

**Comment by yatendra2001** [comment]
hey @superiorsd10 , since it's a feature that requires thinking for business logic from our side. We want to brainstorm on it further and then add comments.

**Comment by superiorsd10** [comment]
> hey @superiorsd10 , since it's a feature that requires thinking for business logic from our side. We want to brainstorm on it further and then add comments.

Okay :) 
I thought it was open to everyone. Thank you!

**Comment by ren276** [comment]
Hey @yatendra2001 
I was installing this too rn and had the same problem but reading the vs starter helped a lot . I suggest that adding the content in the vs started to the first start docs will be good for new contributors

**Comment by yatendra2001** [comment]
@ren276 that's a really nice feedback. Sure we're working towards making our code well documented and creating an awesome contributor guide so anyone can easily setup and contribute.

**Comment by samyakkkk** [comment]
This document will be done in iterations as we work on the code. A separate ticket is not required at the moment.
