### ISSUE TITLE
[Feat]: Notify Users of Extension Updates

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#126]
### Is your feature request related to a problem?

Users are not notified when a new update for the extension is available, potentially missing out on new features and fixes.

### Describe the solution that you'd like

Implement a notification system that alerts users of available updates when the extension is activated. Include a direct link or button in the notification to facilitate easy updating.

### Describe alternatives that you have considered

An alternative could be to include update notifications in the extension's changelog or documentation, but this is less proactive.

### Additional Information

Look into Visual Studio Code's API to see if there are built-in methods for detecting and prompting updates.

### Acceptance Criteria

1. Users receive a notification when an update is available.
2. The notification includes an action that takes the user to the update page.
3. The feature respects the user's notification settings.

**Comment by khurramrizvi** [comment]
@yatendra2001 Please assign this to me, I would like to contribute.

**Comment by yatendra2001** [comment]
Sure @khurramrizvi , assigned to you.

**Comment by samyakkkk** [comment]
Hi @khurramrizvi. Do we have an ETA on this? Thanks.

**Comment by khurramrizvi** [comment]
Hi @samyakkkk,

I am planning to complete by this weekend.

**Comment by yatendra2001** [comment]
issue resolved by #155
