### ISSUE TITLE
[Feat]: Implement Syntax Highlighting in Webview Chat

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#127]
### Is your feature request related to a problem?

The chat interface in the webview currently does not support syntax highlighting, which can make it difficult for users to read and understand code snippets.

### Describe the solution that you'd like

Integrate a syntax highlighting library into the webview chat interface to automatically highlight code snippets in messages. This should support Dart/Flutter syntax at a minimum.

### Describe alternatives that you have considered

-

### Additional Information

Investigate libraries like **PrismJS** or **highlight.js** that can be embedded into webviews for syntax highlighting. Explore media/chat/scripts/main.js to know how currently code markdown to plain text works.  

### Acceptance Criteria

1. Code snippets in chat messages are syntax-highlighted.
2. The highlighting supports Dart/Flutter syntax.
3. The feature does not significantly impact the performance of the chat interface.

**Comment by matiasdev30** [comment]
Hello @yatendra2001, I can made this feature

**Comment by yatendra2001** [comment]
Awesome @matiasdev30 , assigned this to you.

**Comment by yatendra2001** [comment]
@matiasdev30 , can we also make sure that the background colour for the code is black?

Try to look for a showdown library for that inside code. You can find it under the media/chat/scripts/main.js file.

**Comment by samyakkkk** [comment]
Hi @matiasdev30, do we have an ETA for the issue? please let us know and we're happy to help.

**Comment by samyakkkk** [comment]
Reassigning this issue because of no response. 

@matiasdev30 we understand if you were not able to find time. Please feel free to share your interest on the other open issues.

**Comment by wadhia-yash** [comment]
Hi @samyakkkk please assign this issue to me

**Comment by samyakkkk** [comment]
Assigned to you @wadhia-yash. Thanks.

**Comment by yatendra2001** [comment]
closed by #154
