### ISSUE TITLE
[Feat]: Implement Loading Indicator for AI Response Fetching

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#128]
### Is your feature request related to a problem?

Currently, when the AI is fetching a response, the chat interface shows a text placeholder "loading...". This is not visually engaging and can be unclear to some users.

### Describe the solution that you'd like

Replace the "loading..." text with a graphical loading indicator, such as a spinner or progress bar, which provides a more modern and user-friendly visual cue that the system is processing the request.

### Describe alternatives that you have considered

An alternative could be to use an animated character or icon that reflects the AI's "thinking" process, which could add personality to the user interface.

### Additional Information

-

### Acceptance Criteria

1. A graphical loading indicator is displayed when the AI is fetching a response.
2. The indicator is clearly visible and matches the extension's design.
3. The transition from the loading indicator to the AI's response is smooth and without glitches.

**Comment by Mihan786Chistie** [comment]
@yatendra2001 I want to work on this issue, please assign it to me

**Comment by yatendra2001** [comment]
Sure @Mihan786Chistie , make sure to test it thoroughly. Let us know if you need any help.

**Comment by yatendra2001** [comment]
Issues resolved through #129
