### ISSUE TITLE
[Fix]: Use KeyboardEvent.key or KeyboardEvent.code instead of deprecated keyCode

### ISSUE THREAD

**Issue by superiorsd10** [Welltested-AI/fluttergpt#142]
### Description

The project currently uses the deprecated `KeyboardEvent.keyCode` property in several places (e.g. [searchPebblePanel.html](https://github.com/Welltested-AI/fluttergpt/blob/main/assets/pebbles/searchPebblePanel.html#L301) and [main.js](https://github.com/Welltested-AI/fluttergpt/blob/main/media/chat/scripts/main.js#L153)) This property is no longer recommended for use in new code and might be removed from browsers in the future.

### Proposed Solution

We should update the code to use either of the recommended properties:

- `KeyboardEvent.key`: Provides a consistent string representation of the pressed key (e.g., "Enter", "Space", "ArrowUp").
- `KeyboardEvent.code`: Provides a physical key identifier (e.g., "KeyA", "KeyF1", "Digit5").

### Relevant Links

[Link to the Docs mentioning the deprecation of keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

**Comment by superiorsd10** [comment]
Hello @yatendra2001 👋
I want to work on this issue, so please consider assigning it to me.

**Comment by yatendra2001** [comment]
Sure @superiorsd10 go ahead, make sure the changes made are robust and welltested.

**Comment by yatendra2001** [comment]
closed by #150
