### ISSUE TITLE
[GoogleGenerativeAI Error]

### ISSUE THREAD

**Issue by TryHarder13** [Welltested-AI/fluttergpt#145]
### What version are you using?

v0.2.0

### What happened?

[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key=APIKEY: [400 Bad Request] User location is not supported for the API use.

### Steps to reproduce

```bash
1. use fluttergpt create code from description
```

### Relevant log output

```Shell
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent?key=APIKEY: [400 Bad Request] User location is not supported for the API use.
```

**Comment by samyakkkk** [comment]
@TryHarder13 The error happens for regions not supported for Gemini yet. Check[ available regions](https://ai.google.dev/available_regions#available_regions).

There is no clear indication from Google yet on when do they plan to extend the support but we're hoping soon.

**Comment by yatendra2001** [comment]
@TryHarder13 check this issue, it can help in this situation.

#122

**Comment by TryHarder13** [comment]
Thanks for your answer

**Comment by samyakkkk** [comment]
Closing this.
