### ISSUE TITLE
[Feat]: Add Clear Chat Functionality to Chat Interface

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#148]
### Is your feature request related to a problem?

Users currently do not have the option to clear the chat within the extension, which can lead to clutter and difficulty in managing conversations.

### Describe the solution that you'd like

Implement a **'Clear Chat'** feature that allows users to clear their chat conversation from the chat interface. This could be a button that, when pressed, clears the chat window.

### Describe alternatives that you have considered

--

### Additional Information

Ensure that the clear chat functionality is easily accessible but includes a confirmation step to prevent accidental deletion of the chat history.

### Acceptance Criteria

1. A 'Clear Chat' button is present in the chat interface.
2. Activating the feature clears the chat history from the interface.
3. Users are prompted to confirm before the chat is cleared to prevent accidental data loss.

**Comment by superiorsd10** [comment]
Hello @yatendra2001 👋
I want to work on this issue, so please consider assigning it to me.

I'm sharing a design that aligns well with the extension's aesthetics. Further discussion about the design is welcome.

_NOTE: I've used a different font just for the design purpose._

<img src="https://github.com/Welltested-AI/fluttergpt/assets/92971894/ba875f2b-4b14-487d-aac3-73633e9ffa6f" width="275" height="800">

**Comment by yatendra2001** [comment]
@samyakkkk what do you think about this design?

**Comment by yatendra2001** [comment]
@superiorsd10 better if we keep clearchat on topmost rightmost, because here it hinders the experience of chat.

**Comment by superiorsd10** [comment]
> @superiorsd10 better if we keep clearchat on topmost rightmost, because here it hinders the experience of chat.

Okay! So you mean at the right of the **FLUTTERGPT: CHAT VIEW**? Or at the top-right of the chat container?

**Comment by samyakkkk** [comment]
@superiorsd10 on the right of the chat container.

**Comment by superiorsd10** [comment]
> @superiorsd10 on the right of the chat container.

I've made the requested changes, and the clear chat button is now positioned at the top right of the chat container with an opacity of 80%. I appreciate your guidance and would be grateful if you could take a moment to review the updates. Thank you :)

<img src="https://github.com/Welltested-AI/fluttergpt/assets/92971894/42359465-498b-44ad-a582-a5a664a5f48f" width="330" height="800">

<img src="https://github.com/Welltested-AI/fluttergpt/assets/92971894/523226f0-6de1-4888-aa40-7e2f91c2f6ea" width="300" height="200">

**Comment by samyakkkk** [comment]
@superiorsd10 good thinking on keeping it partially transparent. looks good!

**Comment by superiorsd10** [comment]
> @superiorsd10 good thinking on keeping it partially transparent. looks good!

Thank you @samyakkkk :)

So should I start working on it?

**Comment by samyakkkk** [comment]
Yes! Let’s start.

**Comment by superiorsd10** [comment]
Hello @samyakkkk 👋
I've successfully implemented the clear chat functionality. To provide a clearer understanding, I've attached a screen recording demonstrating the new feature in action.

Please take a moment to review the recording and let me know if any further adjustments or changes are needed. Your feedback is highly valuable, and if everything meets the expectations, I'm prepared to proceed with creating a pull request.

### Screen Recordings

https://github.com/Welltested-AI/fluttergpt/assets/92971894/6a121e7b-51e0-4726-9527-9c2076427e99

**Comment by samyakkkk** [comment]
Great job @superiorsd10 ! 

One request: Let's remove the confirmation dialog. We can directly clear the chat when the button is tapped. 


Please create a PR post that. thanks.

**Comment by superiorsd10** [comment]
Hello @samyakkkk 👋
I have made the requested change and submitted a [PR](https://github.com/Welltested-AI/fluttergpt/pull/157) for your review.

Thank you,

**Comment by yatendra2001** [comment]
closing, completed by pr #157
