### ISSUE TITLE
[Feat]: Implement Adaptive Chat Theme Based on VSCode Theme

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#149]
### Is your feature request related to a problem?

The chat interface does not currently adapt to the VSCode theme, which can cause inconsistencies in the user experience for those who switch between light and dark modes.

Check this image:
<img width="1343" alt="Screenshot 2023-12-28 at 1 03 19 PM" src="https://github.com/Welltested-AI/fluttergpt/assets/62821607/8902419b-7279-46bd-87dd-e080375446f0">

### Describe the solution that you'd like

The chat interface should detect the current VSCode theme and adapt its styles accordingly. If the user is in light mode, the chat background and text colors should be light-themed, and if the user is in dark mode, the chat should display dark-themed colors.

### Describe alternatives that you have considered

--

### Additional Information

Investigate how to retrieve the current theme information from VSCode's API and apply the corresponding CSS styles to the chat interface dynamically.

### Acceptance Criteria

1. The chat interface detects the current VSCode theme.
2. The chat background and text colors adapt to match the detected theme.
3. The transition between themes is smooth, without requiring a restart of VSCode or the extension.

**Comment by wadhia-yash** [comment]
Hi @samyakkkk I would like to take up this task

**Comment by samyakkkk** [comment]
Issue resolve in PR #153.
