### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by tanmaymunjal** [Welltested-AI/fluttergpt#15]
Trying to solve issue #9 , ran into another issue screenshotted below, did some digging up to make sure I have not broken something in my local fork and it seems to be the case that even git cloning the main branch and running gives the same error for me in developer extension 

![image](https://user-images.githubusercontent.com/72982935/233825238-08916928-dae9-4131-ba8d-a5db66b5b923.png)

**Comment by samyakkkk** [comment]
@tanmaymunjal thanks for reporting the issue and deciding to take up #9. 

I was not able to reproduce this issue on my Mac. We're trying it on Windows. Would be helpful to have details of your system and VSCode versions.
