### ISSUE TITLE
[Feat]: Implement Workspace Selection Dropdown for '@' Command

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#159]
### Is your feature request related to a problem?

Users need an intuitive way to include their entire workspace as context when typing queries in the chat interface.

### Describe the solution that you'd like

Introduce a feature where typing '@' in the chat input triggers a dropdown menu with the option to select the workspace. This will signal the extension to include the entire workspace as context for the subsequent query.

### Additional Information

**@workspace must be a part of string input.**

Refer this image of co-pilot:
<img width="281" alt="Screenshot 2024-01-05 at 4 07 45 PM" src="https://github.com/Welltested-AI/fluttergpt/assets/62821607/6ab1fa92-c262-4f3f-b1c9-fafdba7b1f43">

### Acceptance Criteria

1. Typing '@' in the chat input shows a dropdown with the workspace selection.
2. Selecting the workspace from the dropdown appends a special tag to the chat input.
3. The UI for the dropdown is consistent with the chat interface and VSCode's design language.

**Comment by wadhia-yash** [comment]
Hi @yatendra2001 I would like to take up the task

**Comment by yatendra2001** [comment]
assigned @wadhia-yash

**Comment by yatendra2001** [comment]
closed by pr #164
