### ISSUE TITLE
[Feat]:  Implement Expandable Chat Input Box

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#161]
### Is your feature request related to a problem?

The current chat input box is limited in size, which can be inconvenient for users who want to write longer queries.

### Describe the solution that you'd like

The chat input box should expand vertically to accommodate longer queries as the user types. Additionally, pressing Shift+Enter should insert a new line in the input box instead of submitting the query.

### Additional Information

Ensure that the expanding functionality does not interfere with the rest of the chat UI and that the input box can be easily resized back to its original size.

### Acceptance Criteria

1. The chat input box expands vertically as the user types more content.
2. Pressing Shift+Enter inserts a new line instead of submitting the query.
3. The UI remains clean and uncluttered, with clear visual cues for expanding and contracting the input box.

**Comment by Mihan786Chistie** [comment]
Hey @yatendra2001, I would like to try solving this issue

**Comment by wadhia-yash** [comment]
Hi @yatendra2001 I've already completed this following issue I will submit the PR soon

**Comment by yatendra2001** [comment]
Hey @Mihan786Chistie since @wadhia-yash already completed this issue in one of his PR, I'm assigning this to him.

**Comment by yatendra2001** [comment]
@wadhia-yash just make sure that there's a space " " when the user hits shift+enter after a @workspace annotation.

**Comment by wadhia-yash** [comment]
Issue resolved in PR #165
