### ISSUE TITLE
[Feat]: Design Frontend UI for Loading Screen During Workspace Query Processing

### ISSUE THREAD

**Issue by yatendra2001** [Welltested-AI/fluttergpt#162]
### Is your feature request related to a problem?

When a user submits a @workspace query, there is no visual feedback indicating the steps the system is taking to process the query.

### Describe the solution that you'd like

Create a frontend UI for the loading screen that appears when a @workspace query is provided. The screen should have three sections: "Accessing work structure(it can take a while in first time)," "Fetching most relevant files," and "Creating a result for you". Each section should visually indicate when it is in progress and when it has been completed.

### Describe alternatives that you have considered

An alternative could be to use a simple progress bar, but a detailed step-by-step UI provides better transparency about the process.

### Additional Information

Take inspiration from GitHub Copilot's UI for designing the loading screen, ensuring it aligns with the visual language of VSCode and provides a clear, informative user experience.

https://github.com/Welltested-AI/fluttergpt/assets/62821607/b3757f92-6f6d-4e33-aeed-c52ae55c3b52

### Acceptance Criteria

1. The loading screen is displayed when a @workspace query is processing.
2. The screen has three distinct sections for each step of the process.
3. Each section has visual indicators for in-progress and completed states.
4. The design is consistent with VSCode's theme and GitHub Copilot's UI aesthetics.

**Comment by wadhia-yash** [comment]
Hi @yatendra2001 would like to take up the task

**Comment by yatendra2001** [comment]
Sure @wadhia-yash assigned.

**Comment by yatendra2001** [comment]
issue resolved by #170
