### ISSUE TITLE
Newly installed user cannot access chat feature

### ISSUE THREAD

**Issue by doitwithdk** [Welltested-AI/fluttergpt#175]
### What version are you using?

v0.2.2

### What happened?

Newly installed users are stuck with a loading indicator and are unable to access the chat features.

### Steps to reproduce

```bash
1. Install the plugin
2. Follow Gemini instructions
3. Observe that the chat feature is not accessible.
```

**Comment by wadhia-yash** [comment]
Completed in PR #176
