### ISSUE TITLE
Build web responsive code using ChatGPT

### ISSUE THREAD

**Issue by tanmoy27112000** [Welltested-AI/fluttergpt#18]

**Comment by samyakkkk** [comment]
This issue'll cover creating responsive web and tablet code for mobile widgets. 

@tanmoy27112000 assigning this to you 🙌

**Comment by tanmoy27112000** [comment]
We  also have to add the documentation. I can add that

**Comment by samyakkkk** [comment]
@tanmoy27112000 yes, indeed very important. Please create another PR 🙏

**Comment by samyakkkk** [comment]
Marking this issue resolved in lieu of #24 and #31!
