### ISSUE TITLE
[Feat]: Must have improved onboarding experience

### ISSUE THREAD

**Issue by doitwithdk** [Welltested-AI/fluttergpt#180]
### Is your feature request related to a problem?

Users installing the extension should be addressed with a better onboarding experience. 

### Describe the solution that you'd like

A step by step flow resolving initial dependencies, and showcasing basic use cases

### Acceptance Criteria

![Group 120](https://github.com/Welltested-AI/fluttergpt/assets/1284396/6db0e39e-b57a-4412-a853-f9bee7c1ccf8)

**Comment by wadhia-yash** [comment]
Hi @doitwithdk I would like to take up the task
