### ISSUE TITLE
HTML rendering of index is broken for lists.

### ISSUE THREAD

**Issue by samyakkkk** [Welltested-AI/fluttergpt#223]
### What version are you using?

v0.2.10

### What happened?

Indexed list response is not correctly handled.

![Screenshot 2024-02-24 at 9 09 35 PM](https://github.com/Welltested-AI/dash-ai/assets/56000318/2560bda2-c0e3-4945-8194-64e593703729)

### Steps to reproduce

```bash
1. Go to Chat
2. Ask a question that shall be returning an indexed list. Like "What are 5 kinds of widgets in  Flutter"
```

**Comment by superiorsd10** [comment]
Hello @samyakkkk 👋

I want to work on this issue, so please consider assigning it to me.

Thank you,

**Comment by samyakkkk** [comment]
assigned @superiorsd10

**Comment by samyakkkk** [comment]
This is released. Closing!
