### ISSUE TITLE
[Feat]: Tutorials or sample prompts

### ISSUE THREAD

**Issue by nicolasvahidzein** [Welltested-AI/fluttergpt#249]
### Describe the problem and solution that you'd like.

I cannot get Dash AI to write integration tests as it is supposed to. Can you please help?

**Comment by samyakkkk** [comment]
Hi @nicolasvahidzein, thanks for sharing this. Please check this [blog](https://www.commanddash.io/blog/5-ways-to-use-inline-code-attachments) that explains how to use multiple code snippet attachments to perform tasks like integration test. Please check point number 5. I hope this helps.

We're also going to be releasing a new update end of this week with specific agents for unit, widget and integration testing which would further make it easier for you.

**Comment by nicolasvahidzein** [comment]
wow. Please please please tell me where to sign up? Or be reminded.

**Comment by nicolasvahidzein** [comment]
@samyakkkk those instructions are a million miles an hour, no instructions and cannot pause. A gif is a bad idea for a tutorial my friend. Where can i find the video of this please?

**Comment by samyakkkk** [comment]
feedback noted, we will update the media on the blog. Meanwhile recorded a quick video for you @nicolasvahidzein:

https://drive.google.com/file/d/1QF_kZCC3uJbTFc9Z4729GUaYSzZ61nEQ/view?usp=sharing.

Please let me how it goes :)

**Comment by nicolasvahidzein** [comment]
You are amazing!! Thanks Samya.

**Comment by nicolasvahidzein** [comment]
completely unrelated but what software are you using for the demo you just made? It is smooth and well animated? WOW.

**Comment by samyakkkk** [comment]
the tool is ScreenStudio @nicolasvahidzein :) 

we've also launched custom agents for testing in the latest release. try using '@test /integration` in Dash Panel! cheers.
