### ISSUE TITLE
Text attached with code snippet shows up as code in sent message

### ISSUE THREAD

**Issue by samyakkkk** [Welltested-AI/fluttergpt#298]
### What version are you using?

latest

### What happened?

<img width="733" alt="Screenshot 2024-06-17 at 2 16 48 PM" src="https://github.com/CommandDash/commanddash/assets/56000318/47043b38-c6e1-4b45-a4f5-5d57ba51f9e8">

### Steps to reproduce

```bash
-
```

**Comment by wadhia-yash** [comment]
This issue is resolved in the following PR #310
