### ISSUE TITLE
Failed to create api service: Error: Failed to get completion from API

### ISSUE THREAD

**Issue by paulpoyyayil** [Welltested-AI/fluttergpt#5]
I created fresh API key and i always get this error
 " Failed to create api service: Error: Failed to get completion from API: Error: Failed to make HTTP request: AxiosError: Request failed with status code 429 "

**Comment by nurdtechie98** [comment]
Hey @paulpoyyayil ,
Thanks for bringing up this issue, the issue seems to be because you are being rate limited by openAI.
ref: https://platform.openai.com/docs/guides/error-codes/api-errors

Just waiting and retrying after sometime should resolve the issue for you.
