### ISSUE TITLE
Handle openAI api error codes gracefully 

### ISSUE THREAD

**Issue by nurdtechie98** [Welltested-AI/fluttergpt#9]
We rely heavily on openAI apis for interaction with GPT. 
In case for some reason openAI requests start failing we should capture the error pass it on in the vscode error popup along with a link to open ai error code documentation https://platform.openai.com/docs/guides/error-codes/api-errors.
This would help the can understand and debug the issue themselves.

**Comment by tanmaymunjal** [comment]
Was looking at the issue, a little new to VS code extension development tbh,  think the below makes sense

![Screenshot from 2023-04-23 17-07-48](https://user-images.githubusercontent.com/72982935/233837548-15553981-c7ff-4379-9edd-baff9f671d92.png)


Would love to hear any feedback on this if anything wrong here

**Comment by samyakkkk** [comment]
@nurdtechie98 please take a look.

**Comment by nurdtechie98** [comment]
Hey @tanmaymunjal ,
Welcome to flutterGPT 🚀 

You are on the right lines but there seems to be a small deviation. Whenever the response is in non 200 range, axios would lead raise an error so the above snippet needs to be added catch part of it.
you can refer the following axios documentation for more info: https://axios-http.com/docs/handling_errors

Looking forward to a PR and happy to help you along the journey

**Comment by tanmaymunjal** [comment]
Got, it. Thanks! Added a pull request with recommended changes

**Comment by samyakkkk** [comment]
Resolve in #21. thanks @tanmaymunjal. closing.
